name: release

on:
  push:
    branches: [main]
    paths-ignore:
      - metadata.json
      - .github
      - README.md

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: package
        run: |
          ignored="! -path $(pwd) "
          for i in $(cat .templateignore); do
              ignored+="! -name $i "
          done
          files=$(find $(pwd) -maxdepth 1 $ignored)
          mkdir kotlin_maven
          cp -r $files ./kotlin_maven
          zip -r kotlin_maven.zip ./kotlin_maven;
          openssl sha256 kotlin_maven.zip | cut -d " " -f2 > kotlin_maven.zip.sha256

      - name: version
        id: version
        run: |
          VERSION=$(jq -r ".version" metadata.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: |
            kotlin_maven.zip
            kotlin_maven.zip.sha256

      - name: bump up version
        run: |
          git clean -dfx
          version=$(jq -r ".version" metadata.json | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo $(jq -r ".version = \"$version\"" metadata.json) | jq . > new_metadata.json
          cat new_metadata.json > metadata.json
          git add metadata.json
          git commit -m ":up: Bumped version to $version"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" master
          
          
        
